[project]
name = "claims-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "nump>=5.5.5.5",
    "pandas>=2.0.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.14.3",
]
